### ISSUE TITLE
Gateway Timeout?

### ISSUE THREAD

**Issue by drone0021** [globaldyne/parfumvault#54]
1. Go to Dashboard
2. Click on 'INFO: no ingredients yet, click [here](http://localhost:8080/index.php?do=ingredients) to add.'
3. Wait
4. Wait
5. 
![2023-03-15_07h55_44](https://user-images.githubusercontent.com/127827532/225230514-9879ba97-75e0-49bc-9c39-4255c481e365.png)
6.
![2023-03-15_07h58_40](https://user-images.githubusercontent.com/127827532/225231262-04513e87-5f29-4edd-8a55-6145a5f76b58.png)

7.
![2023-03-15_08h00_33](https://user-images.githubusercontent.com/127827532/225231355-481d749b-50df-45ed-917f-23c166e2fe87.png)

 - OS: Windows 11
 - Browser: Chrome
 - Version: 111.0.5563.65

**Comment by globaldyne** [comment]
There's currently a bug in Docker running in windows environments preventing PV functioning properly.

Will release a new PV version soon which will bypass this issue.
In the meantime as a workaround, you can downgrade your docker installation to version 4.14.1 or disable **Automatic Proxy Detection** in windows settings or use **podman** instead of docker.

For more info: 

https://github.com/docker/for-win/issues/13159
https://forums.docker.com/t/docker-breaks-php-file-get-contents-and-http-s-stream-wrappers/132885/6
https://podman-desktop.io/downloads
